### ISSUE TITLE
P-wave velocity in general is very ill-recovered.

### ISSUE THREAD

**Issue by haoopan** [larsgeb/psvWave#11]
Dear author，
   psvWave is a great piece of work, and I'm following it.  I would like to ask why p-wave velocity in general is very ill-recovered? I'm looking forward your reply!

Yours 
Sincerely

**Comment by larsgeb** [comment]
Hi there,

Thank you for your interest! 

A good question, one that I also ran into. I discussed it in this work -- https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JB018428, but the gist of it is twofold:

1. The used misfit (L2) is relatively less sensitive to smaller amplitude waves. P-waves for the used moment tensor sources are much smaller, and hence the final sensitivity to the wave velocity parameter is lower, thereby reducing the contrast.
2. The wavelength of P-waves is longer due to the higher velocity, leading to more of a blurring effect on the recovery of the P-wave velocity, thereby reducing the resolution.

Hope this helps, and let me know if you have any other questions.
Lars
